---

- name: Check if Docker runs
  shell:
    systemctl status docker
  tags:
    - always

- name: Prepare storages
  shell: |
    mkdir -p {{ item }}
    restorecon -rv  {{ item }}
    chcon -Rt svirt_sandbox_file_t {{ item }}
  with_items:
    - /var/lib/pgsql/data

### Postgresql issue ###
- name: Check if postgresql database running
  shell: |
    docker ps | grep "{{ db_host }}" || docker start "{{ db_host }}"
  register: database
  ignore_errors: True

- name: Run postgresql in Docker
  shell: |
    docker run -d --name {{ db_host }} -h {{ db_host }} -p 5432:5432 \
        -e POSTGRES_PASSWORD={{ db_pass }} \
        -v /var/lib/pgsql/data:/var/lib/pgsql/data \
        postgres:{{ db_version }}
  when: database.rc != 0
